# Generated by Django 4.2.4 on 2026-03-26 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.CharField(max_length=50, unique=True)),
                ("department", models.CharField(max_length=100)),
                ("current_stock", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="SalesData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("size", models.CharField(max_length=20)),
                ("color", models.CharField(max_length=20)),
                ("daily_sales", models.IntegerField()),
                ("stock_level", models.IntegerField()),
                ("season", models.CharField(max_length=20)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="salesapp.product",
                    ),
                ),
            ],
        ),
    ]
